FROM node:22-slim 
# 作業ディレクトリを/usr/src/appに設定しています。
WORKDIR /usr/src/app

# tzdataはタイムゾーンデータを提供し、tiniはPID 1問題に対処するために使用されます。
RUN apt-get update && apt-get -qq install -y --no-install-recommends \
    tzdata \
    tini \
    curl \
    && rm -rf /var/lib/apt/lists/*

# 環境変数NODE_ENVをdevelopmentに設定しています。
ENV NODE_ENV development

# package.jsonとpackage-lock.jsonをコピーし、所有者をnodeユーザーとnodeグループに設定しています。
COPY --chown=node:node ./my-app/package*.json ./

# package-lock.jsonに記載された依存関係をインストールしています。
RUN npm ci
RUN npm i -D @types/multer
RUN npm install @supabase/supabase-js
RUN npm install sharp
RUN npm install @nestjs/config
# アプリケーションのソースコードをコピーし、所有者をnodeユーザーとnodeグループに設定しています。
COPY --chown=node:node . .
ENTRYPOINT ["/usr/bin/tini","--"]

CMD ["npm","start"]
